version: "2"

services:

  unit_front:
    build: ./assistance/client
    volumes:
      - ./assistance/client:/assistance
    ports:
      - "5000:9876"
    networks:
      - test

  db:
    image: mongo
    container_name: mongodb
    volumes:
      - "mongo-data-test:/data/db"
    networks:
      - test

volumes:
  mongo-data-test:

networks:
  test:
