version: "2"

services:

  assistance:
    build: ./assistance
    volumes:
      - ./assistance:/app
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier
    entrypoint: nodemon --debug server.js

  db:
    image: mongo
    container_name: mongodb
    volumes:
      - "mongo-data:/data/db"
    networks:
      - back-tier

volumes:
  mongo-data:

networks:
  front-tier:
  back-tier:
